# Do not keep production secrets in the repository,
# instead read values from the environment.
<% if ENV["USE_SECRETS"] %>
staging:
  secret_key_base: <%= Sekreto.get_value("rails-secret-key-base") %>

production:
  secret_key_base: <%= Sekreto.get_value("rails-secret-key-base") %>
<% end %>
